import "./Counter/Counter.js"
import "./Profile/ProfileElem/Profile.js"
import "./Profile/Profiles.js"
import "./Navegation/Navegation.js"
import "./PostInsta/PostInsta.js"
import "./Suggestion/Suggestion.js"
